<?php

$available_documents = array(
	"it" => array(
		"cerimonie",
		"concept_banco_riciclaggio_elettrodomestici",
		"concept_sistema_robot_pulizia_fognature",
		"concept_veicoli_piantumazione_alberi",
		"cucina_in_due_fasi",
		"esperienze_e_considerazioni_sulle_piante",
		"giochi_all_aperto",
		"introduzione_alla_meditazione",
		"istruzioni_per_sistemazione_profilo_facebook",
		"riflessioni_produzione_imballaggi",
		"riflessioni_sui_contratti",
		"riflessioni_sul_legno",
		"tecnica_gestione_sogno",
		"concept_carro_raccolta_elettrico",
		"centro_gestione_stoccaggio_legnami",
		"idea_sistema_gestione_processi_giudiziari",
		"analisi_sistemi_trasporto",
		),
	"en" => array(
		"cerimonies",
		"concept_desk_home_appliances_recycling",
		"concept_robot_system_sewers_cleanup",
		"concept_vehicles_trees_planting",
		"two_step_cooking",
		"experiences_and_considerations_about_plants",
		"open_air_games",
		"introduction_to_meditation",
		"instructions_for_fixing_facebook_profile",
		"reflections_about_packaging_production",
		"reflections_about_contracts",
		"reflections_about_wood",
		"dream_management_tecnique",
		"electric_collection_wagon_concept",
		"wood_storage_management_center",
		"idea_judicial_processes_management_system",
		"transport_systems_analysis",
		)
	);